export interface Card {
  id: string,
  category: string,
  phoneId: string,
  itemId: string,
  name: string,
  fullPrice: number,
  price: number,
  screen: string,
  capacity: string,
  color: string,
  year: number,
  ram: string,
  image: string,
  createdAt: string,
  updatedAt: string,
}
